app:
  port: 0.0.0.0:8000
  token_symmetric_key: 12345678901234567890123456789012
  token_expiration: 15m 

database:
  connection_string: "postgresql://postgres:postgres@go-bank-pg:5432/bank?sslmode=disable"
  driver: "postgres"